### ISSUE TITLE
YAMLException: unacceptable kind of an object to dump [object Null]

### ISSUE THREAD

**Issue by tuler** [bendrucker/cfn-nest#2]
I'm trying to use `cfn-nest` with my nested cloudformation YAML templates.
But I get the following error:

```
/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:737
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
      ^
YAMLException: unacceptable kind of an object to dump [object Null]
    at writeNode (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:737:13)
    at writeBlockSequence (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:503:9)
    at writeNode (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:721:9)
    at writeBlockMapping (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:616:10)
    at writeNode (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:709:9)
    at writeBlockMapping (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:616:10)
    at writeNode (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:709:9)
    at writeBlockMapping (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:616:10)
    at writeNode (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:709:9)
    at writeBlockMapping (/Users/tuler/project/node_modules/js-yaml/lib/js-yaml/dumper.js:616:10)
```

**Comment by bendrucker** [comment]
Hmm, can you share the template or a snippet? I'll need to repro this to work on it. Your templates get parsed and re-stringified by https://github.com/bendrucker/cfn-template-stream.

**Comment by tuler** [comment]
Hunting down the issue, I find the problem at this snippet:

```
AvailabilityZone: !Select [ 0, !GetAZs ]
```

Our template is a derived work of:
https://github.com/awslabs/ecs-refarch-cloudformation/blob/18fd28c6c2bc054694c2ab9670c98da06b6171af/infrastructure/vpc.yaml#L65

**Comment by bendrucker** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html

AWS clearly supports that in their parser (since the templates are from awslabs) but their own docs say that syntax is invalid. I'd bet doing `!GetAZs ''` would work for you. I feel like I learn an new quirk of YAML's grammar every week (e.g. `yes` -> `true`) and here we can't even see AWS's code. 

I'm relying on https://github.com/KoharaKazuya/js-yaml-schema-cfn to provide the tag-function syntax. That's where the true fix to align with CFN's internal schema would go. There's also the option for you to just explicitly include the empty string in keeping with the docs and try to emit clearer errors from the cloudformation parser, at least including the offending line for easier debugging.

**Comment by bendrucker** [comment]
A quick Google search (`GetAZs yml`) only turns up examples of people calling with an empty string or explicitly passing `!Ref AWS::Region` in. So perhaps the best solution is to just file a PR with the awslabs project and call it a day. Of course that assumes I'm right about that syntax being the issue 🤞

**Comment by tuler** [comment]
`!GetAZs ""` does work.
Thanks!

**Comment by bendrucker** [comment]
No prob, sending a patch to Amazon so they can update their reference to be right
